#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
#
# Port-drift alarm for zhac-mono-core.
#
# zhac-mono-core/main/ forks the ESP32-S3 gateway layer from zhac-net-core/main/
# (ws_bridge, main, api_*, …). The two live in separate repos, so a change to
# the net-core gateway does NOT automatically reach the mono fork. This script
# records a baseline of the net-core sources mono forks (tools/port-baseline.sha256)
# and fails when any of them changed since the last re-port — the signal to
# review the net-core change, mirror the relevant parts into mono, and re-baseline.
# It does NOT prove the port is correct; it only flags that a review is due.
# See tools/PORTING.md.
#
#   check:   tools/check-port-drift.sh [path-to-net-core]
#   update:  tools/check-port-drift.sh --update [path-to-net-core]   # after a re-port
#
# net-core location resolves to: $1  ->  $ZHAC_NET_CORE  ->  ../../zhac-net-core
# (the sibling-checkout layout mono builds against, and the CI workspace layout).
#
# Exit: 0 = in sync · 1 = drift (files listed) · 2 = usage/environment error.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
files_list="$here/port-files.txt"
baseline="$here/port-baseline.sha256"

mode="check"
if [[ "${1:-}" == "--update" ]]; then mode="update"; shift; fi
netcore="${1:-${ZHAC_NET_CORE:-$here/../../zhac-net-core}}"

[[ -f "$files_list" ]] || { echo "ERROR: missing $files_list" >&2; exit 2; }
if [[ ! -d "$netcore" ]]; then
  echo "ERROR: net-core checkout not found at: $netcore" >&2
  echo "       pass its path as an argument or set \$ZHAC_NET_CORE." >&2
  exit 2
fi
netcore="$(cd "$netcore" && pwd)"

# Portable sha256 (coreutils on Linux/CI, BSD shasum on macOS).
sha() {
  if command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | awk '{print $1}'
  else shasum -a 256 "$1" | awk '{print $1}'; fi
}

tracked() { grep -vE '^\s*(#|$)' "$files_list"; }

if [[ "$mode" == "update" ]]; then
  commit="$(git -C "$netcore" rev-parse HEAD 2>/dev/null || echo unknown)"
  tmp="$(mktemp)"
  {
    echo "# SPDX-FileCopyrightText: 2025-2026 Evgenij Cjura and project contributors"
    echo "# SPDX-License-Identifier: AGPL-3.0-or-later"
    echo "# GENERATED by tools/check-port-drift.sh --update — do not hand-edit."
    echo "# Baseline of zhac-net-core sources that zhac-mono-core/main/ forks."
    echo "# baseline-net-core-commit: $commit"
  } > "$tmp"
  n=0
  while IFS= read -r rel; do
    src="$netcore/$rel"
    [[ -f "$src" ]] || { echo "ERROR: tracked net-core file missing: $src" >&2; rm -f "$tmp"; exit 2; }
    printf '%s  %s\n' "$(sha "$src")" "$rel" >> "$tmp"
    n=$((n+1))
  done < <(tracked)
  mv "$tmp" "$baseline"
  echo "Re-baselined $n file(s) against net-core $commit -> $baseline"
  exit 0
fi

[[ -f "$baseline" ]] || { echo "ERROR: missing $baseline — run: $0 --update $netcore" >&2; exit 2; }

drift=0
while IFS= read -r rel; do
  src="$netcore/$rel"
  [[ -f "$src" ]] || { echo "ERROR: tracked net-core file missing: $src" >&2; exit 2; }
  cur="$(sha "$src")"
  base="$(awk -v p="$rel" '$2==p {print $1}' "$baseline")"
  if [[ -z "$base" ]]; then
    echo "  + $rel  (not in baseline — run --update)" >&2; drift=1
  elif [[ "$base" != "$cur" ]]; then
    echo "  * $rel  (baseline ${base:0:12}… -> now ${cur:0:12}…)" >&2; drift=1
  fi
done < <(tracked)

if [[ "$drift" -ne 0 ]]; then
  echo "" >&2
  echo "PORT DRIFT: net-core gateway sources above changed since the last mono re-port." >&2
  echo "Review each change, mirror the relevant parts into zhac-mono-core/main/, then:" >&2
  echo "    tools/check-port-drift.sh --update $netcore" >&2
  echo "See tools/PORTING.md." >&2
  exit 1
fi

echo "OK: mono fork baseline matches net-core ($(awk '/baseline-net-core-commit/{print $3}' "$baseline"))."
